### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by yamadapc** [yamadapc/node-olhovivo#1]
- [ ] Demonstrate how to pipe data onto MongoDB as GeoJSON
- [ ] Make benchmarks on ideal rate-limiting for maximum throughput public (I have them, need to publish)

**Comment by victorpotasso** [comment]
Hey man, are u planning to get an endpoint to 'Ônibus da madrugada'?
http://olhovivo.sptrans.com.br/#sp?cat=Linha&l=N&l=N

**Comment by yamadapc** [comment]
mm... como assim? isso é um endpoint? esse link que você me mandou está batendo em:

```
http://olhovivo.sptrans.com.br/data/Linha/Buscar?termosBusca=N
```

então usando o wrapper:

``` javascript
async function main () {
  let lines = await olhovivo.queryLines('N');
  console.log(lines);
}
main()
```

por sinal, não é mencionado aqui, mas essa lib provavelmente funciona sem problemas no browser.

**Comment by yamadapc** [comment]
A melhor forma de usar a lib é com caches internos; o que está aqui não é muito relevante
